version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      -aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 337061487615.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-react-app
      - docker tag my-react-app:latest 337061487615.dkr.ecr.ap-south-1.amazonaws.com/my-react-app:latest
      - docker push 337061487615.dkr.ecr.ap-south-1.amazonaws.com/my-react-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
